name: btd
on: workflow_dispatch
jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: true
            max-parallel: 1
            matrix:
                # R: [ 'release', 'oldrel' ]
                R: [ 'release' ]
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        name: Build ${{ matrix.R }}
        steps:
            - uses: actions/checkout@v3
              with:
                  repository: rickhelmus/patRoonDeps
                  token: ${{ secrets.PAT }}
            - name: Setup R
              uses: r-lib/actions/setup-r@v2
              with:
                  r-version: ${{ matrix.R }}
            - name: Pre-Install R deps
              run: |
                  install.packages(c("miniCRAN", "git2r", "devtools", "BiocManager", "rversions"))
                  BiocManager::install(c("Rdisop", "GenomeInfoDbData")) # sometimes needed as dependency may not be picked up...
                  BiocManager::install("ropls") # For KPIC2
                  remotes::install_github("cran/InterpretMSSpectrum@1.3.3") # workaround for https://github.com/cbroeckl/RAMClustR/issues/48
                  BiocManager::install(c("xcms", "qlcMatrix")) # for cliqueMS
                  install.packages("RAMClustR")
                  remotes::install_github(c("blosloos/nontargetData", "blosloos/nontarget"))
                  remotes::install_github("rickhelmus/KPIC2")
                  remotes::install_github("souravc83/fastAdaboost") # For Metaclean, removed from CRAN (9/22)
                  remotes::install_github("KelseyChetnik/MetaClean")
              shell: Rscript {0}
            - name: Make repos
              run: Rscript make_repos.R
            - name: Get repos patch
              run: git diff --binary > patRoonDeps.diff
            - name: Make bundle
              run: Rscript make_bundle.R
            - uses: actions/upload-artifact@v3
              name: Upload artifacts
              with:
                  name: patRoonDeps-artifacts
                  path: |
                      patRoonDeps.diff
                      patRoon-bundle-*.zip
