name: test_prer
on: workflow_dispatch
jobs:
    release:
        runs-on: windows-latest
        name: Make bundle pre-release
        steps:
            - name: Get bundle
              run: |
                  echo hi > bundle.txt
            - name: Make pre-release
              uses: ncipollo/release-action@v1
              with:
                  tag: prerelease
                  name: 'Automated Pre-release'
                  allowUpdates: true
                  artifactErrorsFailBuild: true
                  prerelease: true
                  commit: master
                  makeLatest: true
                  owner: rickhelmus
                  repo: patRoonDeps
                  body: 'This is an automated pre-release of the patRoon bundle. See the installation handbook for details.'
                  artifacts: |
                        bundle.txt
                  removeArtifacts: true
                  replacesArtifacts: true
                  token: ${{ secrets.PAT }}
